services:
  foundry:
    image: felddy/foundryvtt:12.343.0
    hostname: foundryvtt
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_ADMIN_KEY=${ADMIN_KEY}
      - FOUNDRY_LICENSE_KEY=${LICENSE_KEY}
      - FOUNDRY_PROXY_SSL=true
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
