services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: server-docker-syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Melbourne/Australia
    volumes:
      - ./config:/config
      - /media/moo/neptune/server-data/syncthing:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
