---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Private Services:
    - Szurubooru:
        icon: /icons/szurubooru.jpg
        href: http://192.168.20.30:8080
        siteMonitor: http://192.168.20.30:8080
        description: Image booru
        server: local-docker
        container: szurubooru-server-1
    - Ganymede:
        icon: /icons/ganymede.png
        href: http://192.168.20.30:4800
        siteMonitor: http://192.168.20.30:4800
        description: Twitch stream archive server
        server: local-docker
        container: ganymede
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.20.30:8096
        description: Media server
        siteMonitor: http://192.168.20.30:8096
        widget:
            type: jellyfin
            url: http://192.168.20.30:8096
            key: b9d6ef5ae91b4327b99e14aa0803c198
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            enableMediaControl: false # optional, defaults to true
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
        server: local-docker
        container: jellyfin
    - Gluetun:
        icon: gluetun.png
        description: VPN interface
        server: local-docker
        container: torrenting-stack-gluetun-1
    - Firefox:
        icon: firefox.png
        description: Web browser
        href: http://192.168.20.30:5800
        siteMonitor: http://192.168.20.30:5800
        server: local-docker
        container: torrenting-stack-firefox-1
    - qbittorrent:
        icon: qbittorrent.png
        description: Torrent client
        href: http://192.168.20.30:8081
        siteMonitor: http://192.168.20.30:8081
        server: local-docker
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://192.168.20.30:8081
            username: admin
            password: Epicmoo99
            enableLeechProgress: true # optional, defaults to false
            enableLeechSize: true # optional, defaults to false
    - syncthing:
        icon: syncthing.png
        description: File Syncing Tool
        href: http://192.168.20.30:8384
        siteMonitor: http://192.168.20.30:8384
        server: local-docker
        container: syncthing

- Public Services:
    - Immich:
        icon: immich.png
        href: https://photos.oppai.win
        siteMonitor: https://photos.oppai.win
        description: Photo Server
        widget:
            type: immich
            url: http://192.168.20.30:2283
            key: INYoKRIilC4U9fdgwQ97q46fWadLMspd0yE5NTIpIlk
            version: 2 # optional, default is 1
        server: local-docker
        container: immich_server
    - Muse:
        icon: /icons/muse.png
        description: Discord music bot
        server: local-docker
        container: muse-discord-muse-1
    - Foundry:
        icon: /icons/foundry.png
        href: https://dnd.oppai.win
        description: Online D&D game server
        server: local-docker
        container: aaron-foundry-foundry-1
        siteMonitor: https://dnd.oppai.win
    - OwnTracks:
    - Navidrome:
        icon: navidrome.png
        href: https://music.oppai.win
        description: Music server
        server: local-docker
        container: navidrome-navidrome-1
        siteMonitor: https://music.oppai.win
        widget:
            widget:
            type: navidrome
            url: http://192.168.20.30:4533
            user: admin
            token: 797ec5f4120c4eaef5a433ab55fa4125
            salt: c19b2d

- Game Servers:
    - Minecraft Vanilla:
        icon: minecraft.png
        description: Moocraft server from 2022
        widget:
            type: minecraft
            url: udp://oppai.win
        server: local-docker
        container: mcserver
    - Minecraft Bluemap:
        icon: /icons/bluemap.png
        description: Interactive map for vanilla Minecraft server
        href: https://map.oppai.win
        siteMonitor: https://map.oppai.win
        server: local-docker
        container: mcserver
    - Minecraft Plan:
        icon: /icons/plan.png
        description: Player statistics for vanilla Minecraft server
        href: https://info.oppai.win
        siteMonitor: https://info.oppai.win
        server: local-docker
        container: mcserver
    - Minecraft Modded:
        icon: minecraft.png
        description: Persistent modded server from 2025
        widget:
            type: minecraft
            url: udp://modded.oppai.win
    - Terraria:
        icon: terraria.png
        description: 2025 Terraria server
        server: local-docker
        container: terraria

# To add: Torrenting firefox, torrenting qbittorrent, misskey
# Future add: nginx, samba, minecraft, minecraft modded, syncthing
